create table if not exists public.playlists (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    guild_id bigint not null,
    name text not null check (char_length(name) between 1 and 80),
    description text not null default '' check (char_length(description) <= 300),
    created_at timestamptz not null default now(),
    unique (owner_id, guild_id, name)
);

create table if not exists public.playlist_tracks (
    playlist_id bigint not null references public.playlists(id) on delete cascade,
    position integer not null check (position > 0),
    title text not null,
    uri text not null,
    length_ms bigint,
    added_by bigint not null,
    created_at timestamptz not null default now(),
    primary key (playlist_id, position)
);

create table if not exists public.playlist_likes (
    playlist_id bigint not null references public.playlists(id) on delete cascade,
    user_id bigint not null,
    created_at timestamptz not null default now(),
    primary key (playlist_id, user_id)
);

alter table public.playlists enable row level security;
alter table public.playlist_tracks enable row level security;
alter table public.playlist_likes enable row level security;
